### ISSUE TITLE
No output when parsing non-Japanese .zim files

### ISSUE THREAD

**Issue by aaronmueller** [elfxiong/wiktionary-translations-parser#3]
It seems that all non-Japanese editions of Wiktionary will not print any output, aside from the header row and/or error messages (as appropriate). If no error messages appear, my terminal simply hangs after printing the header row and does nothing for upwards of 2 hours. 

The Japanese .zim file is 41M, and it takes about 15 minutes on my laptop to complete. The Uzbek .zim file, however, is 32M; it doesn't print anything after 45 minutes of seeming inactivity. French displays the same behavior.

**Comment by elfxiong** [comment]
I also get normal output from `de` edition. I'll test `vi` edition as well later. 

If with latest `parser.py` you get nothing in output, there might be log generated in `log/parser.log`, since any TypeError are ignored and directed to the log instead of showing in console. (Edit: It is not necessarily the problem but there is a slight chance that it is.)

**Comment by elfxiong** [comment]
I put some print statement in `generate_translation_tuples()` in `fr` parser, and it seems that `fr` parser are running but never yields anything. It is getting the `headword` and `head_lang`, so perhaps the requirement to yield is too strict?

Another thing to note is that, since `fr` parser currently only generate output for translations, it will not generate anything visible when it is parsing words that don't have translations. Once I made `ja` and `de` parsers to print pronunciations, which is a field that is more common than translations, they "look faster" because they output much more and there is no break between outputs.

**Comment by sshearing** [comment]
Got the Russian parser at least running without crashes, but also not getting output. I'll be working on it all day today. It's also not printing pronunciations yet.

**Comment by elfxiong** [comment]
Okay, I just tried `vi` parser on `.zim`. Similar to `fr`, `ru` and `uz` mentioned above, it only generated 4 lines in a minute. So I let it print out each page word (the word that appear at the top of the page) and find out that more than 99.99% of the time it didn't capture anything from the pages other than the page word. Some possible reasons that I can think of:
1. Most pages are indeed quite empty (at least for `vi` edition), containing only a part of speech and a sentence of explanation;
2. The contents we are interested in are nested further down in the tree - sometimes headers (`<h2>` `<h3>` etc.) are not the direct children of `mw-content-text` but rather "grandchildren" or "great grandchildren" etc.. (I found out this because `vi` parser is supposed to print part of speech even if there is no translations, but it is not even printing part of speech.) So we need to find a better way to iterate through them - children of `mw-content-text` might not always work.
